spring:
  config:
    import: optional:configserver:http://localhost:8888
    enabled: true
  application:
    name: cloudconfig
  cloud:
    vault:
      host: 127.0.0.1
      port: 8200
      scheme: http
      authentication: TOKEN
      token: hvs.vDKhcr2lL2qjog6vkKY1hb4l
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
       