spring:
  config:
    import: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
    enabled: true
  application:
    name: cloudconfig
  cloud:
  
    vault:
      host: localhost
      port: 8200
      scheme: http
      token: hvs.rbRZj1Rwf10BoDeAAubUa0h8
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
       