spring:
  config:
    import: optional:configserver:http://localhost:8888
    enabled: true
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
       